### PR TITLE
Avoid using log's private API to construct records

### LINKED ISSUE #309: bug report: slog-stdlog depends log::__private_api_log and slog-stdlog break with log v0.4.15
when updating log to 0.4.15, the `log::__private_api_log` change and slog-stdlog is broken

> ```
> error[E0061]: this function takes 4 arguments but 3 arguments were supplied
>     --> /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-stdlog-4.1.0/lib.rs:244:9
>      |
> 244  |         log::__private_api_log(format_args!("{}", lazy), level, &(target, info.module(), info.file(), info.line()));
>      |         ^^^^^^^^^^^^^^^^^^^^^^ ------------------------  -----  -------------------------------------------------- supplied 3 arguments
>      |         |
>      |         expected 4 arguments
>      |
> note: function defined here
>     --> /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.15/src/lib.rs:1576:8
>      |
> 1576 | pub fn __private_api_log(
>      |        ^^^^^^^^^^^^^^^^^
> 
> 
> ```

although this `log::__private_api_log` is exported, we all know this is a private function and hope no one uses it

could slog team bump a new version to fix it?

### PR DESCRIPTION
**Pull request by Techcable**
Previously this API was required to work around rust-lang/log#95

Thanks to the inclusion of a `RecordBuilder` (PR rust-lang/log#211) it is no longer required.

This fixes slog-rs/slog#309
This supersedes PR #20 (please close it)

I have added a comment about supporting the `log/kv_unstable` feature in the future.
Not supporting this feature doesn't break backwards compat, because the
old usage of the private API didn't support it either. Therefore, this
new code doesn't break or remove anything that was already existing.
However,from a feature-completeness standpoint it would be nice to have
this in the future.

I will open an issue on the slog repo to track this feature in the future.
However, if someone *really* wants to use this feature in the meantime, I humbly
suggest they use `slog` directly, since we probably have a better notion of key/values ;)

@dpc please merge and close #20 (I don't have write access here)

### CODE REVIEW

**Comment by Techcable** [comment]
Don't make a release just yet though. I'm migrating to Github Actions.

**Comment by dpc** [comment]
> Don't make a release just yet though. I'm migrating to Github Actions.

Now you do.

**Comment by dpc** [comment]
I have added you to the crate owners, no?

**Comment by Techcable** [comment]
> I have added you to the crate owners, no?

Yes. Now you have :)
